"""
Django settings for mtaasafi project.

Generated by 'django-admin startproject' using Django 1.8.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'vbx#4b_e1(2g)nedbcxo4n5)lw(lf8d3rp!7g975f64tn01sqg'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'gcm',
    'djangobower',
    'sorl.thumbnail',

    'base_map',
    'web_app'
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'mtaasafi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mtaasafi.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'SET_DATABASE_NAME',
        'USER': 'SET_USERNAME',
        'PASSWORD': 'SET_PASSWORD',
        'HOST': 'SET_HOST'
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = 'staticfiles'

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)

STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'djangobower.finders.BowerFinder',
)

BOWER_COMPONENTS_ROOT = os.path.join(STATIC_ROOT, 'components')

BOWER_INSTALLED_APPS = (
    'jquery',
    'polymer#^1.0.0',
    'PolymerElements/iron-flex-layout',
    'PolymerElements/iron-ajax',
    'PolymerElements/iron-icon',
    'PolymerElements/iron-icons',
    'PolymerElements/iron-iconset',
    'PolymerElements/iron-iconset-svg',
    'PolymerElements/iron-image',
    'PolymerElements/iron-collapse',
    'PolymerElements/iron-meta',
    'PolymerElements/paper-header-panel',
    'PolymerElements/paper-scroll-header-panel',
    'PolymerElements/paper-tabs',
    'PolymerElements/paper-button',
    'PolymerElements/paper-icon-button',
    'PolymerElements/paper-checkbox',
    'PolymerElements/paper-item',
    'PolymerElements/neon-animation',
    'polymer-filters',
    'leaflet-map-component',
)

try:
    from local_settings import *
except ImportError:
    pass